export const copy = {
  app: {
    name: 'Zenth',
    tagline: 'set it. it grows.',
    description: 'Your autonomous SEO agent. Give it your product — it handles everything.',
  },
  landing: {
    heroTitle: 'Zenth',
    heroTagline: 'set it. it grows.',
    heroSubheading: 'Your autonomous SEO agent. Give it your product — it handles everything.',
    ctaPrimary: 'Start free',
    ctaSecondary: 'See how it works',
    featuresTitle: 'Everything SEO. Nothing manual.',
    featuresLabel: 'what it does',
    featuresHeading1: 'One agent.',
    featuresHeading2: 'Every SEO task.',
    featuresSubheading: 'Zenth connects to your site, learns your niche, and runs the full SEO workflow — research, writing, publishing, and tracking — on autopilot.',
    pricingTitle: 'Simple, transparent pricing.',
    pricingSubtitle: 'Start free. Scale as you grow.',
    pricingLabel: 'pricing',
    pricingHeadingNew: 'Simple, site-based pricing.',
    pricingSubheadingNew: 'Pay for what you connect. Cancel anytime.',
    mostPopular: 'Most popular',
    ctaHeading1: 'Ready to let your SEO',
    ctaHeading2: 'run itself?',
    ctaSubheading: 'Connect your site in under 2 hours. First article live within 24 hours.',
    ctaButton: 'Start building →',
    footerTagline: 'set it. it grows.',
  },
  dashboard: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    agentFeedTitle: 'Agent Activity',
    keywordTitle: 'Keyword Opportunities',
    trafficChartTitle: 'Organic Traffic',
    approvalBannerText: 'articles waiting for your approval',
    approvalBannerCta: 'Review now',
  },
  content: {
    pageTitle: 'Content',
    pageSubtitle: 'Review and approve AI-generated articles',
    approveLabel: 'Approve',
    editLabel: 'Edit',
    skipLabel: 'Skip',
    expandLabel: 'View details',
    collapseLabel: 'Collapse',
    emptyState: 'No articles pending approval. The agent is working on new content.',
  },
  keywords: {
    pageTitle: 'Keywords',
    pageSubtitle: 'Discover and track keyword opportunities',
    searchPlaceholder: 'Search keywords...',
    filterIntent: 'Intent',
    filterDifficulty: 'Difficulty',
    filterStatus: 'Status',
    clusterToggle: 'Cluster view',
    emptyState: 'No keywords found matching your filters.',
    columns: {
      keyword: 'Keyword',
      volume: 'Volume',
      difficulty: 'Difficulty',
      intent: 'Intent',
      status: 'Status',
      trend: 'Trend',
    },
  },
  settings: {
    pageTitle: 'Settings',
    sections: {
      profile: 'Profile',
      sites: 'Connected Sites',
      integrations: 'Integrations',
      notifications: 'Notifications',
      billing: 'Billing',
      theme: 'Appearance',
    },
    saveLabel: 'Save changes',
    cancelLabel: 'Cancel',
  },
  onboarding: {
    title: 'Welcome to Zenth',
    subtitle: 'Let\'s set up your autonomous SEO agent in 4 steps.',
    nextLabel: 'Continue',
    backLabel: 'Back',
    finishLabel: 'Launch my agent',
    skipLabel: 'Skip for now',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    notFound: 'Page not found.',
    unauthorized: 'You need to sign in to access this.',
  },
  empty: {
    default: 'Nothing here yet.',
    keywords: 'No keywords discovered yet.',
    content: 'No content drafts yet.',
    backlinks: 'No backlinks tracked yet.',
  },
}
